# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigOptionKeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'str'), (1, 'int'), (2, 'float'), (3, 'bool')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataEntryKeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'str'), (1, 'int'), (2, 'float'), (3, 'bool')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
