# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_auth', '0002_profile_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
