# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0002_auto_20170504_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefeedback',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
