# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20170614_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Long and detailed description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='Unique short name used on URLs.', primary_key=True, serialize=False, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Long and detailed description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(help_text='Unique short name used on URLs.', primary_key=True, serialize=False, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Long and detailed description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(help_text='Unique short name used on URLs.', primary_key=True, serialize=False, verbose_name='Short name'),
        ),
    ]
