# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customconfigoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'str'), (1, 'int'), (2, 'float')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
