# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dataentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configoption',
            name='type',
            field=models.IntegerField(choices=[(0, 'str'), (1, 'int'), (2, 'float'), (3, 'bool')]),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='type',
            field=models.IntegerField(choices=[(0, 'str'), (1, 'int'), (2, 'float'), (3, 'bool')]),
        ),
    ]
