# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20161207_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.Sprint'),
        ),
    ]
