# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(help_text='Unique short name used on URLs.', primary_key=True, serialize=False, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A one-phrase description used in listings.', verbose_name='Description')),
                ('school_id', models.CharField(blank=True, max_length=50)),
                ('since', models.DateField(blank=True, null=True)),
                ('syllabus', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('program', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('bibliography', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(help_text='Unique short name used on URLs.', primary_key=True, serialize=False, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A one-phrase description used in listings.', verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='faculty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
