# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 03:49
from __future__ import unicode_literals

import codeschool.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0028_merge'),
        ('core', '0003_root_pages_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExhibit',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('points_total', models.IntegerField(blank=True, help_text="Points may be awarded in specific contexts (e.g., associated with a quiz or in a list of activities) and in Codeschool's generic ranking system.", verbose_name='value')),
                ('stars_total', models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Number of stars the activity is worth (fractional stars are accepted). Stars are optional bonus points for special accomplishments that can be used to trade "special powers" in codeschool.', max_digits=5, verbose_name='stars')),
                ('difficulty', models.IntegerField(blank=True, choices=[(0, 'Trivial'), (1, 'Very Easy'), (2, 'Easy'), (3, 'Regular'), (4, 'Hard'), (5, 'Very Hard'), (6, 'Challenge!')])),
                ('author_name', models.CharField(blank=True, help_text="The author's name, if not the same user as the question owner.", max_length=100, verbose_name="Author's name")),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProgrammingLanguage')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'verbose_name': 'activity',
                'abstract': False,
            },
            bases=(codeschool.models.AbsoluteUrlMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ExhibitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.TextField()),
                ('image', models.ImageField(upload_to='images/code_exhibit/')),
                ('num_votes', models.IntegerField(default=int)),
                ('exhibit', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='code_exhibit.CodeExhibit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('votes_from', models.ManyToManyField(related_name='_exhibitentry_votes_from_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exhibitentry',
            unique_together=set([('user', 'exhibit')]),
        ),
    ]
