# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_exhibit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexhibit',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProgrammingLanguage'),
        ),
    ]
