# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_exhibit', '0002_auto_20161012_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeexhibit',
            options={'verbose_name': 'Code exhibit', 'verbose_name_plural': 'Code exhibits'},
        ),
        migrations.AlterField(
            model_name='exhibitentry',
            name='image',
            field=models.FileField(upload_to='images/code_exhibit/'),
        ),
    ]
