# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_exhibit', '0004_auto_20161020_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexhibit',
            name='closed',
            field=models.BooleanField(default=bool, help_text='A closed activity does not accept new submissions.', verbose_name='Closed to submissions'),
        ),
    ]
