# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_exhibit', '0005_codeexhibit_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexhibit',
            name='disabled',
            field=models.BooleanField(default=bool, help_text='Activities can be automatically disabled when Codeshool encounters an error. This usually produces a message saved on the .disabled_message attribute.', verbose_name='Disabled'),
        ),
        migrations.AddField(
            model_name='codeexhibit',
            name='disabled_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codeexhibit',
            name='group_submission',
            field=models.BooleanField(default=bool, help_text='If enabled, submissions are registered to groups instead of individual students.', verbose_name='Group submissions'),
        ),
        migrations.AddField(
            model_name='codeexhibit',
            name='max_group_size',
            field=models.IntegerField(default=6, help_text='If group submission is enabled, define the maximum size of a group.', verbose_name='Maximum group size'),
        ),
        migrations.AddField(
            model_name='codeexhibit',
            name='visible',
            field=models.BooleanField(default=bool, help_text='Makes activity invisible to users.', verbose_name='Invisible'),
        ),
        migrations.AlterField(
            model_name='codeexhibit',
            name='closed',
            field=models.BooleanField(default=bool, help_text='A closed activity does not accept new submissions, but users can see that they still exist.', verbose_name='Closed to submissions'),
        ),
    ]
