# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_exhibit', '0006_auto_20161212_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexhibit',
            name='has_correct_submissions',
            field=models.BooleanField(default=bool),
        ),
        migrations.AddField(
            model_name='codeexhibit',
            name='has_submissions',
            field=models.BooleanField(default=bool),
        ),
    ]
