# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('comments', models.TextField(blank=True)),
                ('is_binary', models.BooleanField(default=False)),
                ('is_language', models.BooleanField(default=False)),
                ('is_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('files.fileformat',),
        ),
    ]
