# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='classrooms_as_staff', to=settings.AUTH_USER_MODEL, verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms_as_student', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
