formats = [
    'markdown:Markdown',
    'text:Plain Text',
    'html:HTML',
    'css:CSS',
    'latex:LaTeX',
    'tex:TeX',
    'ruby:Ruby',
    'java:Java',
    'javascript:Javascript',
    'perl:Perl',
    'haskell:Haskell',
    'julia:Julia',
    'go:Go',
    'pytuga:Pytuguês',
    'python:Python 3.5',
    'python2:Python 2.7',
    'c:C99 (gcc compiler)',
    'cpp:C++11',
]
