# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_remove_textquestion_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='disabled_message',
            field=models.TextField(blank=True, help_text='Messsage explaining why the activity was disabled.', verbose_name='Disabled message'),
        ),
    ]
