# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170421_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='passphrase',
            field=models.CharField(
                help_text='The passphrase is case-insensitive. We tolerate small typing errors.', max_length=200, verbose_name='Passphrase'),
        ),
    ]
