# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0002_auto_20161219_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Grade given for users that choose these option (value=0, for an incorrect choice and value=100 for a correct one).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Value'),
        ),
    ]
