# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0003_auto_20161219_2051'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='multiplechoiceprogress',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='multiplechoicesubmission',
            managers=[
            ],
        ),
    ]
