# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 21:25
from __future__ import unicode_literals

import codeschool.lms.activity_lists.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='Unique short name used on URLs.', verbose_name='Short name')),
                ('short_description', models.CharField(help_text='A short one-sentence description used in listings.', max_length=140, verbose_name='short description')),
                ('long_description', wagtail.wagtailcore.fields.RichTextField(help_text='Long and detailed description.', verbose_name='Description')),
                ('icon', models.CharField(default='code', help_text='Name of the material design icon. Check full list at: https://material.io/icons', max_length=20, validators=[codeschool.lms.activity_lists.validators.material_icon_validator], verbose_name='Optional icon')),
            ],
            options={
                'verbose_name': 'List of activities',
                'verbose_name_plural': 'Lists of activities',
            },
        ),
    ]
