# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('gamification', '0001_initial'),
        ('activities', '0001_initial'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(help_text='A brief description for the lesson.', verbose_name='title')),
                ('date', models.DateField(blank=True, help_text='Date scheduled for this lesson.', null=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.RenameModel(
            old_name='CalendarPage',
            new_name='Calendar',
        ),
        migrations.RemoveField(
            model_name='lessonpage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='page',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LessonPage',
        ),
        migrations.AddField(
            model_name='lessoninfo',
            name='calendar',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='courses.Calendar'),
        ),
        migrations.AddField(
            model_name='lessoninfo',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='courses.Lesson'),
        ),
    ]
