# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:55
from __future__ import unicode_literals

import codeschool.lms.courses.models.course
from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161213_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='short name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='subscription_passphrase',
            field=models.CharField(blank=True, default=codeschool.lms.courses.models.course.random_subscription_passphase, help_text='A passphrase/word that students must enter to subscribe in the course. Leave empty if no passphrase should be necessary.', max_length=140, verbose_name='subscription passphrase'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='syllabus',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
