# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161213_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
