# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', 'data_0001_initial_with_formats'),
        ('question_codingio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingioquestion',
            name='owner',
            field=models.ForeignKey(help_text="The activity's owner.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_codingio.CodingIoQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='teststate',
            unique_together=set([('question', 'hash')]),
        ),
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together=set([('question', 'language')]),
        ),
    ]
