# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:11
from __future__ import unicode_literals

import codeschool.questions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_submission_final_feedback'),
        ('coding_io', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingIoFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Feedback')),
                ('for_pre_tests', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(codeschool.questions.models.QuestionMixin, 'activities.feedback'),
        ),
    ]
