# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 21:11
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0003_auto_20170505_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='teststate',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
