# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0004_codingiofeedback_is_pre_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingiofeedback',
            old_name='is_pre_test',
            new_name='for_pre_test',
        ),
    ]
