# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0004_auto_20170610_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.TextField(blank=True, help_text='This optional field controls which code should be placed in the source code editor when a question is opened. This is useful to put boilerplate or even a full program that the student should modify. It is possible to configure a global per-language boilerplate and leave this field blank.', verbose_name='placeholder source code')),
            ],
            options={
                'verbose_name': 'placeholder',
                'verbose_name_plural': 'placeholders',
            },
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='source_hash',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='validated',
            field=models.BooleanField(default=False, help_text='Verify if the answer key source is validated', verbose_name='is validated?'),
        ),
    ]
