# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0005_auto_20161214_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingioquestion',
            old_name='post_tests_size',
            new_name='num_post_tests',
        ),
        migrations.RenameField(
            model_name='codingioquestion',
            old_name='pre_tests_size',
            new_name='num_pre_tests',
        ),
        migrations.RemoveField(
            model_name='codingioquestion',
            name='test_state',
        ),
        migrations.AlterUniqueTogether(
            name='teststate',
            unique_together=set([('question', 'hash')]),
        ),
    ]
