# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0006_auto_20161214_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingiofeedback',
            old_name='feedback',
            new_name='json_feedback',
        ),
    ]
