# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0007_auto_20161214_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='error_message',
            field=models.TextField(blank=True, help_text='If an error is found on post-validation, an error message is stored in here.', verbose_name='error message'),
        ),
        migrations.AddField(
            model_name='codingioquestion',
            name='error_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='codingioquestion',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingioquestion',
            name='ignore_programming_errors',
            field=models.BooleanField(default=False, help_text='Mark this if you want to ignore programming errors this time. It will ignore errors once, but you still have to fix the source of those errors to make the question become operational.'),
        ),
        migrations.AlterField(
            model_name='codingiofeedback',
            name='for_pre_test',
            field=models.BooleanField(default=False, help_text='True if its grading in the pre-test phase.', verbose_name='Grading pre-test?'),
        ),
    ]
