# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0008_auto_20161215_2101'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='codingiosubmission',
            managers=[
            ],
        ),
    ]
