# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='hash',
            field=models.CharField(max_length=32),
        ),
    ]
