# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='final_grade',
            new_name='final_grade_pc',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='given_grade',
            new_name='given_grade_pc',
        ),
    ]
