# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status_changed',
        ),
    ]
