# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20161214_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Feedback'),
        ),
    ]
