# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_submission_final_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='activities.Submission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.Feedback'),
        ),
    ]
