# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20161214_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='manual_grading',
            field=models.BooleanField(default=True, help_text='True if feedback was created manually by a human.'),
        ),
    ]
