# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_feedback_human_grader'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='num_recycles',
            field=models.IntegerField(default=0),
        ),
    ]
