# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_submission_num_recycles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='human_grader',
            new_name='grader_user',
        ),
    ]
