# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:01
from __future__ import unicode_literals

import codeschool.lms.activities.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20161214_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Similar to given_grade, but can account for additional factors such as delay penalties or for any other reason the teacher may want to override the student's grade.", max_digits=6, null=True, validators=[codeschool.lms.activities.models.validators.grade_validator], verbose_name='final grade'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='given_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='This grade is given by the auto-grader and represents the grade for the response before accounting for any bonuses or penalties.', max_digits=6, null=True, validators=[codeschool.lms.activities.models.validators.grade_validator], verbose_name='percentage of maximum grade'),
        ),
    ]
