# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20161215_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='final_score',
            new_name='final_grade',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grader_user',
            field=models.ForeignKey(blank=True, help_text='User that performed the manual grading.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
