# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 08:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrade',
            name='post_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='usergrade',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grades', to='sparta.SpartaActivity'),
        ),
    ]
