# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericquestion',
            name='help_text',
            field=models.TextField(blank=True, help_text='Additional explanation that is displayed under the input form.', verbose_name='Help text'),
        ),
    ]
