# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericquestion',
            name='disabled_message',
            field=models.TextField(
                blank=True, help_text='Messsage explaining why the activity was disabled.', verbose_name='Disabled message'),
        ),
    ]
