# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numeric', '0002_numericquestion_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numericquestion',
            options={'verbose_name': 'Numeric question', 'verbose_name_plural': 'Numeric questions'},
        ),
    ]
