# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numeric', '0003_auto_20161219_1335'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='numericprogress',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='numericsubmission',
            managers=[
            ],
        ),
    ]
